### ISSUE TITLE
Diagrama do fluxo

### ISSUE THREAD

**Issue by jpmmatias** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e2-proj-int-t5-mochileiros#16]

**Comment by MarianaRodrigues97** [comment]
![Untitled](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e2-proj-int-t5-mochileiros/assets/145329783/54fe9b27-b69d-4957-a602-05399e69652e)
